#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /etc/sysconfig/heat-params
    owner: "root:root"
    permissions: "0644"
    content: |
      MASTER_IP=$MASTER_IP
      FLANNEL_SUBNET=$FLANNEL_SUBNET
      FLANNEL_BACKEND_TYPE=host-gw